### ISSUE TITLE
建议：测试总结-差异分析中，每个列表中加入‘序号’列。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#101]
建议：测试总结-差异分析中，每个列表中加入‘序号’列。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76830226-c2f15880-685f-11ea-96d7-1732000aa233.png)

**Comment by sying2000** [comment]
页面中，下面还有2个列表呢

**Comment by wsc940506** [comment]
已修改

**Comment by wsc940506** [comment]
![image](https://user-images.githubusercontent.com/49634376/77907654-90624980-72bc-11ea-907d-0762f5535ad6.png)
