### ISSUE TITLE
回归测试后，测试需求分析-测试项及测试方法-填写新增的测试项属性时，追踪关系 没法追踪到对应的更改申请单号。建议追踪关系栏修改为可编辑，或在选择列表中加入更改申请单。图17

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#102]
回归测试后，测试需求分析-测试项及测试方法-填写新增的测试项属性时，追踪关系 没法追踪到对应的更改申请单号。建议追踪关系栏修改为可编辑，或在选择列表中加入更改申请单。图17
![图17](https://user-images.githubusercontent.com/50563222/76825992-50c84600-6856-11ea-8e16-4a0f15efff16.jpg)

**Comment by wsc940506** [comment]
现在暂时先不修改

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/77147528-6ba1f100-6ac8-11ea-80d4-fc2aabb334c0.png)
