### ISSUE TITLE
测试需求分析-测试项及测试方法-检查项和度量项列表，导入检查列表后，不能添加删除 或编辑记录。图4

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#107]
测试需求分析-测试项及测试方法-检查项和度量项列表，导入检查列表后，不能添加删除 或编辑记录。图4
![图4](https://user-images.githubusercontent.com/50563222/77521572-dcc51800-6ebd-11ea-96ca-f58a7d5fc0fa.jpg)

**Comment by wsc940506** [comment]
未找到原因，我在服务器上试是可以的
