### ISSUE TITLE
测试设计-设计测试用例-需求树，在测试用例上，点击右键，选择复制测试用例时，出现的页面不对。应该和在测试项上，右键点击复制用例时，出现的界面一样。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#113]
测试设计-设计测试用例-需求树，在测试用例上，点击右键，选择复制测试用例时，出现的页面不对。应该和在测试项上，右键点击复制用例时，出现的界面一样。

**Comment by wsc940506** [comment]
测试项下点击复制测试用例是可以复制该轮次的测试用例，测试用例下点击复制测试用例是在该测试用例的父节点下复制该测试用例。需要重新对需求
