### ISSUE TITLE
测试执行-提交执行的测试用例-测试用例基本信息页面中-没有追踪关系数据。图13. 同样，在测试设计阶段-设计测试用例，测试项基本信息里就没有了追踪关系信息。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#116]
![图13](https://user-images.githubusercontent.com/50563222/77606931-d6817b00-6f53-11ea-97e1-e97fafaad174.jpg)

**Comment by wsc940506** [comment]
在添加测试项和测试子项时未添加追踪关系，导致后面的追踪关系里面没有数据（现在发现的原因）。

**Comment by wsc940506** [comment]
![image](https://user-images.githubusercontent.com/49634376/77906914-580e3b80-72bb-11ea-83b5-a4aea8f533d1.png)

**Comment by wsc940506** [comment]
已修改
