### ISSUE TITLE
新建项目完成后，需要在首页中打开一次，才能进行测试依据管理操作。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#26]
新建项目完成后，需要在首页中打开一次，才能进行测试依据管理操作。应该是 用户刚刚 新建的项目，默认为的打开状态，可以直接对其进行操作。

**Comment by wsc940506** [comment]
新建项目完成后，项目是按照时间从近到远排序的，点击第一个项目名称即可进入项目定制。

**Comment by wsc940506** [comment]
该问题不影响操作，如果客户提出来，再进行修改。
