### ISSUE TITLE
测试需求分析-需求树中-选择度量项、检查项时，右侧页面中标签页弄反了：度量项 弄成了检查项，检查项弄成了度量项页面。如图

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#28]
测试需求分析-需求树中-选择度量项、检查项时，右侧页面中标签页弄反了：度量项 弄成了检查项，检查项弄成了度量项页面。如图
![度量项标签页](https://user-images.githubusercontent.com/50563222/74712667-cf36c580-5261-11ea-9706-f2eeace16f88.png)

**Comment by wsc940506** [comment]
已修改
