### ISSUE TITLE
度量项和检查项页面中，目前导入导出、增加保存功能没有实现。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#29]
度量项和检查项页面中，目前导入导出、增加保存功能没有实现。

**Comment by wsc940506** [comment]
导入导出是与excel相关联的，这部分内容腾飞和超越在新能源造价项目中正在实现，需要他们完成后，我请教超越copy到云平台项目中。保存功能已经实现。

**Comment by wsc940506** [comment]
已修改，现在添加了导入功能，导出功能还没有实现。

**Comment by wsc940506** [comment]
excel里面的通过与否需要填‘是’或‘否’，因为前端控件无法识别图标

**Comment by wsc940506** [comment]
已解决导出功能

**Comment by wsc940506** [comment]
已解决服务器导出问题
