### ISSUE TITLE
度量项和检查项页面中，检查项页面中，是否通过列，应该是check样式。如图

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#30]
度量项和检查项页面中，检查项页面中，是否通过列，应该是check样式。如图
![检查项、度量项结果应该是check样式](https://user-images.githubusercontent.com/50563222/74713989-99471080-5264-11ea-8e84-e29855b5eb6e.jpg)

**Comment by wsc940506** [comment]
现在可以保存上数据，check样式现在未想好如何做。

**Comment by wsc940506** [comment]
已解决
