### ISSUE TITLE
度量项、检查项 页面中检查结果信息保存不上。如图

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#31]
![度量和检查项结果保存不上](https://user-images.githubusercontent.com/50563222/74714471-90a30a00-5265-11ea-8d87-42e019569eae.jpg)

**Comment by wsc940506** [comment]
这个问题是因为通过与否 是bool字段，只能填true，false或者0,1。换成check样式后该问题即可解决。
