### ISSUE TITLE
在设计测试步骤时 ，实例名相同时，不能合并处理。如图

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#33]
![实例参数不能合并1](https://user-images.githubusercontent.com/50563222/74714655-ee375680-5265-11ea-96be-1440599b4e72.jpg)
![实例参数不能合并2](https://user-images.githubusercontent.com/50563222/74714663-f2fc0a80-5265-11ea-8925-e34dc4bc215f.jpg)

**Comment by wsc940506** [comment]
已修改

**Comment by sying2000** [comment]
验证失败

**Comment by sying2000** [comment]
验证如图13-1/13-2所示
![13-1](https://user-images.githubusercontent.com/50563222/75447308-129cdc80-59a4-11ea-8d4f-f76f2bfe80e3.jpg)
![13-2](https://user-images.githubusercontent.com/50563222/75447318-1597cd00-59a4-11ea-8f81-56b0e704e8d2.jpg)

**Comment by wsc940506** [comment]
已修改
![企业微信截图_15828764593291](https://user-images.githubusercontent.com/49634376/75521418-a91fdb00-5a42-11ea-8602-adf0ef9c3856.png)
![企业微信截图_15828764703170](https://user-images.githubusercontent.com/49634376/75521420-aa510800-5a42-11ea-8357-baddf997975c.png)

**Comment by sying2000** [comment]
已验证
