### ISSUE TITLE
测试用例执行--只能保存当前步骤的结果，前面步骤的结果随即消失。如图

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#37]
测试用例执行--只能保存当前步骤的结果，前面步骤的结果随即消失。如图
![测试步骤结果保存不完整](https://user-images.githubusercontent.com/50563222/74716527-b29e8b80-5269-11ea-9cfa-116fdec5d60e.jpg)

**Comment by sying2000** [comment]
在如图界面中保存不上。当查看执行结果的时候，能保存上。

**Comment by wsc940506** [comment]
已解决
