### ISSUE TITLE
启动回归测试后，在测试需求分析树中显示不出来第二轮的测试。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#38]
启动回归测试后，在测试需求分析树中显示不出来第二轮的测试。但是在回归启动选择用例页面中能显示，如图。
![回归 启动](https://user-images.githubusercontent.com/50563222/74724339-167b8100-5277-11ea-8719-b3301bac1a6d.jpg)
![回归轮次不显示](https://user-images.githubusercontent.com/50563222/74724372-1ed3bc00-5277-11ea-8fd7-ec86589b0c09.jpg)

**Comment by wsc940506** [comment]
需要将树结构签入后，再选择回归的测试用例。

**Comment by wsc940506** [comment]
操作问题，已解决。
