### ISSUE TITLE
测试工具执行，要记录执行次数。点击“+”展开时，出现的每次的执行时间、人员、实测结果（这里是链接，链接到原始结果文件）、删除。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#40]
没有用户要求：测试工具执行，要记录执行次数。点击“+”展开时，出现的每次的执行时间、人员、实测结果（这里是链接，链接到原始结果文件）、删除。

**Comment by sying2000** [comment]
在测试用例执行情况查询页面中没改，但在提交执行的测试用例页面中修改了。没改彻底。

**Comment by wsc940506** [comment]
已修改其中一个问题。

**Comment by wsc940506** [comment]
测试工具这边先保持现在这样。
