### ISSUE TITLE
测试执行-提交执行的测试用例页面中，当点击树上的某个测试项时，右侧菜单中 测试用例统计标签页中，没有列表数据显示。如图19。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#41]
测试执行-提交执行的测试用例页面中，当点击树上的某个测试项时，右侧菜单中 测试用例统计标签页中，没有列表数据显示。如图19。

**Comment by wsc940506** [comment]
测试执行时需要出库的内容全部入库，入库后就会显示测试用例统计标签页。
