### ISSUE TITLE
测试执行-测试执行情况查询页面中，当点击树上的测试项或测试子项时，右侧的页面显示为空白，建议参考 提交执行的测试用例 页面。如图20

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#42]
测试执行-测试执行情况查询页面中，当点击树上的测试项或测试子项时，右侧的页面显示为空白，建议参考 提交执行的测试用例 页面。如图20
![图20](https://user-images.githubusercontent.com/50563222/74803676-c5bc6480-5318-11ea-9f7b-4b62a0368d46.jpg)

**Comment by wsc940506** [comment]
已修改
