### ISSUE TITLE
测试用例设计-树结构中，在添加测试项的时候，建议可以从测试依据中选择测试项的名称。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#43]
测试用例设计-树结构中，在添加测试项的时候，建议可以从测试依据中选择测试项的名称。

**Comment by wsc940506** [comment]
根据年前的要求，测试用例设计-树结构中，不设有添加测试项，测试项是在测试需求分析-测试项及测试方法中添加。
