### ISSUE TITLE
测试需求分析-文档概述-引用文档中，没办法上传文档内容。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#45]
测试需求分析-文档概述-引用文档中，没办法上传文档内容。

**Comment by wsc940506** [comment]
上传的文档没有对应的格式。后端无接口，需要提供对应的文档。当时做的时候是先在页面中展示出来对应按钮，有文档后再处理文档，添加至数据库。

**Comment by wsc940506** [comment]
经过讨论，该功能是将文档上传至服务器。已解决。
