### ISSUE TITLE
测试需求分析-文档概述-术语和缩略语页面中，没有导入功能。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#51]

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/75953007-3f447d00-5eeb-11ea-8b47-8ac83352baf1.png)
![image](https://user-images.githubusercontent.com/49634376/75953024-4cfa0280-5eeb-11ea-9a85-50753d3752f3.png)
