### ISSUE TITLE
测试需求分析-测试项及测试方法-树中的检查项、度量项页面页面中，通过与否列，当选择不通过时，系统保存为通过。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#52]

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/75840068-6294fc80-5e05-11ea-8666-08591da41388.png)
![image](https://user-images.githubusercontent.com/49634376/75840083-69bc0a80-5e05-11ea-9ec8-fffbbb310e09.png)
