### ISSUE TITLE
测试设计-设计测试用例-在测试用例的 测试实例设计标签页中，页面中列表名和列表内容显示错位。如图14，14-1

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#58]
测试设计-设计测试用例-在测试用例的 测试实例设计标签页中，页面中列表名和列表内容显示错位。如图14，14-1
![Uploading 图14.jpg…]()
![图14-1](https://user-images.githubusercontent.com/50563222/75448551-5f81b280-59a6-11ea-9562-56e3e0f977f7.jpg)

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/75935938-b2ce9600-5ebb-11ea-83d2-71597d5f6a03.png)
![image](https://user-images.githubusercontent.com/49634376/75935951-bb26d100-5ebb-11ea-8db6-461d0d3a7cf1.png)
