### ISSUE TITLE
建议去掉 测试子项中的 测试子项标签页，因为测试子项项目没有子项了。如图15

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#59]
建议去掉 测试子项中的 测试子项标签页，因为测试子项项目没有子项了。如图15
![图15](https://user-images.githubusercontent.com/50563222/75449603-38c47b80-59a8-11ea-99ad-2a4f16d78ebb.jpg)

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/75760370-23699b80-5d72-11ea-8dba-021a274446f6.png)
