### ISSUE TITLE
测试用例设计时，测试集成工具项，没有空选项，导致测试用例如不使用工具时，没办法设计生成用例。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#61]
测试用例设计时，测试集成工具项，没有空选项，导致测试用例如不使用工具时，没办法设计生成用例。

**Comment by wsc940506** [comment]
已解决
![image](https://user-images.githubusercontent.com/49634376/75521085-e9cb2480-5a41-11ea-8423-263e59a8dbad.png)

**Comment by wsc940506** [comment]
空选项为 -- 系统自带
