### ISSUE TITLE
测试执行-测试问题记录页面中，当点击测试项或测试子项时，应该显示当前测试项或测试子项下的问题列表，不应该是空白页。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#64]
测试执行-测试问题记录页面中，当点击测试项或测试子项时，应该显示当前测试项或测试子项下的问题列表，不应该是空白页。

**Comment by wsc940506** [comment]
已修改，不知后续会出现什么样的问题，可能需要大范围调整后端代码。现阶段先展示数据。
![image](https://user-images.githubusercontent.com/49634376/75948640-fb4b7b00-5ede-11ea-8f2b-0f6c7f8e681b.png)
![image](https://user-images.githubusercontent.com/49634376/75948650-030b1f80-5edf-11ea-9f45-bbe73c493ffc.png)
