### ISSUE TITLE
测试执行-测试执行情况查询页面中，当点击树上的测试项或测试子项时，右侧的页面显示为空白，建议参考 提交执行的测试用例 页面，显示测试用例执行情况。如图20

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#65]
测试执行-测试执行情况查询页面中，当点击树上的测试项或测试子项时，右侧的页面显示为空白，建议参考 提交执行的测试用例 页面，显示测试用例执行情况。如图20
![图20](https://user-images.githubusercontent.com/50563222/75513743-b16f1a80-5a30-11ea-94e4-053f1aff53f0.jpg)

**Comment by wsc940506** [comment]
已修改

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/75948149-a22f1780-5edd-11ea-9dde-47eb1f492ec5.png)
![image](https://user-images.githubusercontent.com/49634376/75948168-afe49d00-5edd-11ea-99b8-d7ad772cc52c.png)
