### ISSUE TITLE
测试需求分析-测试项及测试方法页面中，在需求树上的测试项级，右键点击，“添加同级”时，弹出的添加项是“测试子项、测试用例”项，不是测试项。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#68]
测试需求分析-测试项及测试方法页面中，在需求树上的测试项级，右键点击，“添加同级”时，弹出的添加项是“测试子项、测试用例”项，不是测试项。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76283980-00416d80-62d7-11ea-92e7-4fcec7966f16.png)
