### ISSUE TITLE
测试设计-文档概述-术语和缩略语中的导入方式和 测试需求分析模块中的不一致。建议改成一致

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#69]
测试设计-文档概述-术语和缩略语中的导入方式和 测试需求分析模块中的不一致。建议改成一致

**Comment by wsc940506** [comment]
导入是一致的，只不过文件有差别，当excel文件只有sheet1时，直接显示，当有多个sheet时，会出现选择sheet的样式。

**Comment by sying2000** [comment]
对于术语和缩略语来说，导入只限于对一批记录的导入，不存在对某个记录导入详细文件的情况。所以应该和测试需求分析--术语和缩略语导入一样，批量导入数据到列表中，同时去掉目前系统中每条记录后面的‘导入’按钮。图7
![图7](https://user-images.githubusercontent.com/50563222/76728889-d5ea2700-6792-11ea-95d2-12f3a4d4b624.jpg)
