### ISSUE TITLE
测试执行-测试问题记录-页面中，问题处理措施列数据 显示错误。如图13 

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#80]
测试执行-测试问题记录-页面中，问题处理措施列数据 显示错误。如图13 
![图13](https://user-images.githubusercontent.com/50563222/76281637-9f169b80-62d0-11ea-9600-3023559329df.jpg)

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76487496-956e6e80-645d-11ea-8512-13640c4c8e69.png)
