### ISSUE TITLE
测试需求分析-文档概述-引用文档中，上传第二个附件时，提示“文件重复"不能上传。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#87]
测试需求分析-文档概述-引用文档中，上传第二个附件时，提示“文件重复"不能上传。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76729519-4f364980-6794-11ea-8a33-30339db5ea35.png)

**Comment by wsc940506** [comment]
![image](https://user-images.githubusercontent.com/49634376/76729694-b48a3a80-6794-11ea-9a04-1e41c7873a8c.png)

**Comment by sying2000** [comment]
测试需求分析-文档概述-引用文档中，上传第二个以上附件时，提示“文件已存在"。
