### ISSUE TITLE
测试需求分析-文档概述-术语和缩略语中，在修改某条记录的页面中，想取消操作时，点击‘取消’按钮，或‘X’号，系统没反应。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#88]
测试需求分析-文档概述-术语和缩略语中，在修改某条记录的页面中，想取消操作时，点击‘取消’按钮，或‘X’号，系统没反应。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76729573-65dca080-6794-11ea-9355-bb2ce7c0da35.png)
![image](https://user-images.githubusercontent.com/49634376/76729594-71c86280-6794-11ea-930b-076dc661de76.png)
![image](https://user-images.githubusercontent.com/49634376/76729617-8278d880-6794-11ea-8124-91a42a526562.png)
