### ISSUE TITLE
测试需求分析-测试项及测试方法-测试需求树，在检查项和度量项属性页面中，测试集成工具选项中，当不选择工具时，没法进行操作

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#91]
测试需求分析-测试项及测试方法-测试需求树，在检查项和度量项属性页面中，测试集成工具选项中，当不选择工具时，没法进行操作。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76730400-1d25e700-6796-11ea-86b3-7faa76728488.png)

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76730457-3a5ab580-6796-11ea-9d6b-922f80d674ac.png)

**Comment by wsc940506** [comment]
其中测试用例也存在这个问题，一并修改了
