### ISSUE TITLE
测试设计-文档概述-引用文档页面中，接收日期列数据没有显示；操作 项中缺少操作（参考需求分析中的文档概述）、且不能导入文档。图6

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#92]
测试设计-文档概述-引用文档页面中，接收日期列数据没有显示；操作 项中缺少操作（参考需求分析中的文档概述）、且不能导入文档。图6
![图6](https://user-images.githubusercontent.com/50563222/76728202-092bb680-6791-11ea-8025-6028af960346.jpg)

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76737806-6b41e700-67a4-11ea-9997-4821a129df05.png)
![image](https://user-images.githubusercontent.com/49634376/76737835-74cb4f00-67a4-11ea-90e0-ae5bdefe6064.png)
