### ISSUE TITLE
测试执行-提交执行的测试用例-对判断 部分执行的结果存在错误。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#96]
测试执行-提交执行的测试用例-对判断 部分执行的结果存在错误。对用例执行结果判断应该是：执行失败（只要有一步执行失败就算失败，不管步骤执行完与否）执行通过（全部步骤均执行通过）部分执行（步骤没有执行完整，且没有执行失败的用例）。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/77145576-e61c4200-6ac3-11ea-8e0b-12d6feb21642.png)
![image](https://user-images.githubusercontent.com/49634376/77145583-ecaab980-6ac3-11ea-82dc-0c5183bfb138.png)
