### ISSUE TITLE
测试执行-测试问题记录，点击测试项下，应该显示当前测试项的问题列表数据，目前没有数据没有显示出来。同理，点击测试项、测试级别、轮次的时，也要显示出当前对应级别项的数据。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#97]
测试执行-测试问题记录，点击测试项下，应该显示当前测试项的问题列表数据，目前没有数据没有显示出来。同理，点击测试项、测试级别、轮次的时，也要显示出当前对应级别项的数据。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/77145624-06e49780-6ac4-11ea-9811-3b22ba772de3.png)
![image](https://user-images.githubusercontent.com/49634376/77145658-2085df00-6ac4-11ea-9100-bd41fd162a4b.png)
