### ISSUE TITLE
建议：在回归测试启动时，加个检测，检测下入库没有，如果没有就提示入库。不然忘了入库，启动后需求分析模块中不显示。

### ISSUE THREAD

**Issue by sying2000** [wsc940506/tc_doc#99]
建议：在回归测试启动时，加个检测，检测下入库没有，如果没有就提示入库。不然忘了入库，启动后需求分析模块中不显示。

**Comment by wsc940506** [comment]
已修改
![image](https://user-images.githubusercontent.com/49634376/76828611-5759bc00-685c-11ea-809f-201b655516c1.png)
